services:
  coffy:
    build: .
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

    networks:
      - n8n-docker_default

networks:
  n8n-docker_default:
    external: true
